name = "cloudflare-internship-dev"
type = "webpack"
account_id = "583a96465836f65b14b5dd637a829357"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "webpack.config.js"

[env.staging]
name="cloudflare-internship-stage"

[env.prod]
name="cloudflare-internship"
